# T2.1: Exercicio CSV con PANDAS

Práctica de lectura de arquivos CSV e conversión. Terás que completar o seguinte código de exemplo onde corresponda.

Utiliza como dataset os arquivos CSV dos centros educativos en Galicia: <https://www.edu.xunta.gal/centroseducativos/>

Importar a libraría **pandas** (lembra instalala con conda se non a tes: `conda install pandas`)

In [2]:
import pandas as pd
import os, tempfile

Ler ficheiro CSV e gardalo un dataframe:

In [3]:
coruna_df = pd.read_csv("C:/Users/gabriel.antonio.edre/Documents/main/GIT/Tareas_SBD/Tarea_T2.1_SBD/acoruna.csv")

**Completa**:

In [4]:
lugo_df = pd.read_csv("C:/Users/gabriel.antonio.edre/Documents/main/GIT/Tareas_SBD/Tarea_T2.1_SBD/lugo.csv")
ourense_df = pd.read_csv("C:/Users/gabriel.antonio.edre/Documents/main/GIT/Tareas_SBD/Tarea_T2.1_SBD/ourense.csv")
pontevedra_df = pd.read_csv("C:/Users/gabriel.antonio.edre/Documents/main/GIT/Tareas_SBD/Tarea_T2.1_SBD/pontevedra.csv")

**Completa**: Carga o resto de dataframes e gárdao na variable df: <https://realpython.com/pandas-merge-join-and-concat/>

In [5]:
df = pd.concat([coruna_df, lugo_df, ourense_df, pontevedra_df], ignore_index = True)

Amosar o dataframe

In [6]:
df

,Código,Nome,Enderezo,Concello,Provincia,Cód. postal,Teléfono,Tipo de centro,COORDENADA_X,COORDENADA_Y,TITULARIDADE,ENSINO_CONCERTADO,DEPENDENTE
0,15000016,CEIP Plurilingüe San Marcos,Campo da Feira s/n,Abegondo,A Coruña,15318.0,881880201,CEIP,43.229183,-8.286580,Pública,Non,Si
1,15000107,CEIP A Maía,"Rúa Peregrina, s/n (Bertamiráns)",Ames,A Coruña,15220.0,881866002,CEIP,42.867485,-8.657342,Pública,Non,Si
2,15000132,CPR Plurilingüe Alca,Lugar Biduído de Arriba 36,Ames,A Coruña,15895.0,981531103,CPR,42.846325,-8.600729,Privada,Si,Non
3,15000338,CPI As Mirandas,Avenida Celso Emilio Ferreiro 4,Ares,A Coruña,15624.0,881930020,CPI,43.429363,-8.246173,Pública,Non,Si
4,15000363,CEIP Ponte dos Brozos,"Avenida Arsenio Iglesias, 34 (Sabon)",Arteixo,A Coruña,15142.0,881960506,CEIP,43.306938,-8.510333,Pública,Non,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1634,36025220,CAD FDYE-Galicia,Avenida das Camelias 53,Vigo,Pontevedra,36211.0,680831166,CAD,-8.729750,42.229722,Privada,Non,Non
1635,36025232,CEMU Profesional Agrupación Musical do Rosal,"Rúa Couso, s/n - Auditorio",O Rosal,Pontevedra,36770.0,NaN,CEMU,-8.835709,41.934625,Privada,Non,Non
1636,36025244,CPR Nortempo Formación,Rúa Ourense 2,Vigo,Pontevedra,36211.0,900104220,CPR,-8.730249,42.225970,Privada,Non,Non
1637,36025256,CPR Big Formación Peniche,Rúa López Mora 2,Vigo,Pontevedra,36208.0,NaN,CPR,0.000000,0.000000,Privada,Non,Non
1638,36025268,EMUSPR de Salvaterra de Miño,Rúa Rosalía de Castro 78,Salvaterra de Miño,Pontevedra,36450.0,NaN,EMUSPR,-8.499848,42.083714,Privada,Non,Non

Amosar as primeiras filas do dataframe (cabeceira)

In [7]:
df.head()

,Código,Nome,Enderezo,Concello,Provincia,Cód. postal,Teléfono,Tipo de centro,COORDENADA_X,COORDENADA_Y,TITULARIDADE,ENSINO_CONCERTADO,DEPENDENTE
0,15000016,CEIP Plurilingüe San Marcos,Campo da Feira s/n,Abegondo,A Coruña,15318.0,881880201,CEIP,43.229183,-8.286580,Pública,Non,Si
1,15000107,CEIP A Maía,"Rúa Peregrina, s/n (Bertamiráns)",Ames,A Coruña,15220.0,881866002,CEIP,42.867485,-8.657342,Pública,Non,Si
2,15000132,CPR Plurilingüe Alca,Lugar Biduído de Arriba 36,Ames,A Coruña,15895.0,981531103,CPR,42.846325,-8.600729,Privada,Si,Non
3,15000338,CPI As Mirandas,Avenida Celso Emilio Ferreiro 4,Ares,A Coruña,15624.0,881930020,CPI,43.429363,-8.246173,Pública,Non,Si
4,15000363,CEIP Ponte dos Brozos,"Avenida Arsenio Iglesias, 34 (Sabon)",Arteixo,A Coruña,15142.0,881960506,CEIP,43.306938,-8.510333,Pública,Non,Si

Amosar as últimas filas do dataframe

In [8]:
df.tail()

,Código,Nome,Enderezo,Concello,Provincia,Cód. postal,Teléfono,Tipo de centro,COORDENADA_X,COORDENADA_Y,TITULARIDADE,ENSINO_CONCERTADO,DEPENDENTE
1634,36025220,CAD FDYE-Galicia,Avenida das Camelias 53,Vigo,Pontevedra,36211.0,680831166,CAD,-8.729750,42.229722,Privada,Non,Non
1635,36025232,CEMU Profesional Agrupación Musical do Rosal,"Rúa Couso, s/n - Auditorio",O Rosal,Pontevedra,36770.0,NaN,CEMU,-8.835709,41.934625,Privada,Non,Non
1636,36025244,CPR Nortempo Formación,Rúa Ourense 2,Vigo,Pontevedra,36211.0,900104220,CPR,-8.730249,42.225970,Privada,Non,Non
1637,36025256,CPR Big Formación Peniche,Rúa López Mora 2,Vigo,Pontevedra,36208.0,NaN,CPR,0.000000,0.000000,Privada,Non,Non
1638,36025268,EMUSPR de Salvaterra de Miño,Rúa Rosalía de Castro 78,Salvaterra de Miño,Pontevedra,36450.0,NaN,EMUSPR,-8.499848,42.083714,Privada,Non,Non

Amosar a "forma" ou dimensións do dataframe (filas e columnas)

In [9]:
df.shape

(1639, 13)

Amosar algunhas estatísticas por defecto

In [10]:
df.describe()

             Código   Cód. postal  COORDENADA_X  COORDENADA_Y
count  1.639000e+03   1638.000000   1639.000000   1639.000000
mean   2.657808e+07  27002.887668     35.420011     -1.359246
std    9.286126e+06   9304.941902     17.882334     17.449197
min    1.500002e+07  15001.000000    -13.488744     -9.269669
25%    1.502641e+07  15701.000000     42.208822     -8.689238
50%    2.702094e+07  27875.000000     42.517906     -8.400874
75%    3.601115e+07  36214.000000     43.021791     -7.566911
max    3.602527e+07  36995.000000     43.738419     43.741764

In [11]:
# seleccionar a columna de "Concello" como serie
df['Concello']

# mostrar o tipo de selección
type(df['Concello'])

# Outro xeito de seleccionar series
df.TITULARIDADE

# mostrar o tipo de selección
type(df.Concello)

#seleccionar a columna de "Nome" como Dataframe
df[['Nome']]

# mostrar o tipo de selección
type(df[['Nome']])

# seleccionar varias columnas "Código" e "Nome"
df[['Código','Nome']]

# Mirar o tipo do resultado
type(df[['Código','Nome']])

# Mirar o tipo do argumento que lle pasas a df para facer a selección ['elemento1','elemento2']
type(['Código','Nome'])

list

A completar tamén:

In [12]:
# A resolver, pista: <https://www.geeksforgeeks.org/selecting-rows-in-pandas-dataframe-based-on-conditions/>

# Seleccionar centros que sexan de titularidade privada. Cantos hai?
# privados_df = df[(df.TITULARIDADE == 'Privada')]
# privados_df.head(500)
# print(len(privados_df))

# Seleccionar centros que teñan ensinanzas concertados. Cantos hai?
# concertados_df = df[(df.ENSINO_CONCERTADO == 'Si')]
# concertados_df.head(500)
# print(len(concertados_df))

# Hai algún centro con ensinanzas concertadas dependente da Consellería?
# concertadosDependientes_df = concertados_df[(concertados_df.DEPENDENTE == 'Si')]
# concertadosDependientes_df.head(500)
# print(len(concertadosDependientes_df)) #No parece haber ningún concertado dependiente

# Seleccionar centros de titularidade pública de Coruña. Cantos hai?
# publicos_df = df[(df.TITULARIDADE == 'Pública') & (df.Provincia == 'A Coruña')]
# publicos_df.head(500)
# print(len(publicos_df))

# Seleccionar centros de titularidade pública de Lugo. Cantos hai?
# publicos_df = df[(df.TITULARIDADE == 'Pública') & (df.Provincia == 'Lugo')]
# publicos_df.head(500)
# print(len(publicos_df))

# Seleccionar centros de titularidade pública de Ourense. Cantos hai?
# publicos_df = df[(df.TITULARIDADE == 'Pública') & (df.Provincia == 'Ourense')]
# publicos_df.head(500)
# print(len(publicos_df))

# Seleccionar centros de titularidade pública de Pontevedra. Cantos hai?
# publicos_df = df[(df.TITULARIDADE == 'Pública') & (df.Provincia == 'Pontevedra')]
# publicos_df.head(500)
# print(len(publicos_df))

# Seleccionar centros de tipo: CIFP de cada unha das catro provincias. Cantos hai?
# CIFP_df = df[(df['Tipo de centro'] == 'CIFP')]
# CIFP_df.head(500)
# print(len(CIFP_df))

# Seleccionar centros de tipo: CPI, CEIP e IES de cada unha das catro provincias. Cantos hai?
# tipoCentro_df = df[(df['Tipo de centro'] == 'CPI') | (df['Tipo de centro'] == 'CEIP') | (df['Tipo de centro'] == 'IES')]
# tipoCentro_df.head(500)
# print(len(tipoCentro_df))

# Seleccionar o número de centros por concello.
# centroProvincia_df = df.groupby('Provincia')['Código'].size()
# centroProvincia_df.head(500)

# Seleccionar o número de centros de cada tipo por concello.
# tipoCentroProvincia_df = df.groupby(['Provincia', 'Tipo de centro'])['Código'].size()
# tipoCentroProvincia_df.head(500)

# Limpando datos con erros: Dime qué podes limpar e como nestes datos.
# df = df.dropna()
# df.head(500)

Garda o dataframe total resultante nos seguintes formatos (e logo volve abrilo nese formato e mostra a cabeceira):

**CSV**

In [13]:
arquivo_temporal = os.path.join(tempfile.mktemp())

df.to_csv(arquivo_temporal)

print(arquivo_temporal)

C:\Users\GABRIE~1.EDR\AppData\Local\Temp\tmp59dbbh4c

**Excel**

Pasa a formato excel.

In [14]:
df.to_excel('archivo.xlsx', index=False)

ModuleNotFoundError: No module named 'openpyxl'

**JSON**

Pasa a formato JSON.

(Coidado cos índices se xuntaches os dataframes)

**XML**

Pasa a formato XML:

**PARQUET**

Pasa a formato parquet. Podes precisar as dependencias para **.parquet**: 

    `conda install pyarrow fastparquet´